### ISSUE TITLE
It would be nice to see this in awesome-go

### ISSUE THREAD

**Issue by dcormier** [bsm/redis-lock#10]
As the title states, it would be nice to see this listen on [awesome-go](https://awesome-go.com/) to make it more discoverable.

**Comment by dim** [comment]
@dcormier would you be able to submit a PR to awesome-go?

**Comment by dcormier** [comment]
I don't have time in the foreseeable future.

**Comment by fishioon** [comment]
https://github.com/avelino/awesome-go/pull/1966
Now redis-lock is listen on  awesome-go
