### ISSUE TITLE
IsLocked returns true even if lock timed out on Redis server

### ISSUE THREAD

**Issue by snowzach** [bsm/redis-lock#12]
It might be intentional however it is plausible that the lock could have timed out on the Redis server yet IsLocked will return true. Perhaps maybe add another function CheckIsLocked() which will verify by reading the lock value to ensure that this instance still holds the lock.

**Comment by fuxiangduan** [comment]
I do no understand the IsLocked mean? look the example, 
```
	// Sleep and check if still locked afterwards.
	time.Sleep(200 * time.Millisecond)
	if locker.IsLocked() {
		t.Log("My lock has expired!")
	}
```
it's mean lock is expired, but why, and look the source, lock(client) cannot monitor lock(redis) is expired, feel the auther give up this project, 对不对

**Comment by tomjamescn** [comment]
I have met this problem too!

I think this api is ambiguous.

**Comment by dim** [comment]
Deprecated in favour of https://github.com/bsm/redislock
