### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by dobegor** [bsm/redis-lock#4]
```file: 'file:///Users/egor/go/src/github.com/bsm/redis-lock/lock.go'
severity: 'Error'
message: 'code in directory /Users/egor/go/src/github.com/go-redis/redis expects import "gopkg.in/redis.v5"'
at: '10,2'
source: ''
```

Cause: 0a3c01f764b4864e340afce6ffa26c97da6927bb

Please revert back to v.5, because this breaks importing this package _and_ using gopkg-versioned version of `go-redis`, which is kinda essential.

**Comment by dobegor** [comment]
Reproducible even on fresh (zeroed GOPATH) install:
```
$ go get -u -v github.com/bsm/redis-lock
github.com/bsm/redis-lock (download)
github.com/go-redis/redis (download)
package github.com/go-redis/redis: code in directory /Users/egor/go/src/github.com/go-redis/redis expects import "gopkg.in/redis.v5"
```

**Comment by dim** [comment]
Sorry, I jumped ahead a little too quickly on this one. Go-redis' v6 release is due in the next few days and will fix the problem, There is a v5 of redis-lock available at https://github.com/bsm/redis-lock/releases/tag/v5.0.0, but I will add a default branch for this too

**Comment by dim** [comment]
I made `v5` the default branch for now, until go-redis.v6 is out.
